### PR TITLE
Shellcheck script linting

### PR DESCRIPTION
**Pull request by sand194**

### CODE REVIEW

**Review by pgronkievitz — COMMENTED** [review]
I'd add shfmt to keep shell code formatted

**Comment by finloop** [comment]
Suggestion(non-blocking): Run only when shell files change: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths

**Comment by sand194** [comment]
I don't know if I should keep the -w flag in shfmt but other than that I think it works as desired

**Review by finloop — APPROVED** [review]
LGTM, GJ @sand194

**Pull request merged**
